base: add support for adb root
Expose the ADBRoot interface to priv-apps

Change-Id: I493f3322b19b6474bf8899a103156794ef412ae2

Whitelist settings to use adb root permission

Change-Id: I93122777c82fad33be04fcce002ba1a8468cacbe

Fix ADB root system API extension

* Fixes checkapi:
  out/soong/.intermediates/frameworks/base/system-api-stubs-docs/android_common/current-apicheck/srcjars/android/Manifest.java:3435:
  error: Added field android.Manifest.permission.ADBROOT to the system API [AddedField]

  error: Added package android.adb to the system API [AddedPackage]

Change-Id: Idd509c31d961a0b20fac8cccd2c83c6bf23c5a38

ADBRootService: Deal with binder death

Change-Id: Id5e4a455ea16a4158086816abf093d8f603d4e49

ADBRootService: Remove redundant permission check

 * First of all, the check is performed in a helper class, one can
   easily bypass it by directly issuing the binder API.
 * On the other hand, enforceCallingOrSelfPermission allows root and
   system UID to do everything, i.e., any process running in system UID
   is allowed to pass the check, including Settings app, thus it's
   simply a no-op.

Change-Id: I82f58d6165c2ef35c61047d5899de3e8ca6f7f39